name: mlops
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.11
  - ipykernel
  - nbconvert
  - nbformat
  - python-dotenv
  - seaborn
  - snowflake-snowpark-python
  - scikit-learn=1.3.0
  - xgboost
  - absl-py
  - anyio
  - cloudpickle
  - numpy
  - packaging
  - pandas
  - pyyaml
  - typing-extensions
  - snowflake-ml-python
  - snowflake-snowpark-python
  - scikit-learn
  - prefect
  - mlflow
  - fastapi 
  - uvicorn

