name: SnowflakeMLOPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  data_processing:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Jupyter and Micromamba
        run: |
          curl -L micro.mamba.pm/install.sh | bash
          micromamba shell init --shell bash --root-prefix=~/micromamba
          echo 'export PATH="$HOME/micromamba/bin:$PATH"' >> $GITHUB_ENV
          source ~/micromamba/etc/profile.d/mamba.sh
          micromamba create --name mlops --file environment.yml --yes
          echo 'micromamba activate mlops' >> $GITHUB_ENV

      - name: Print working directory
        run: pwd

      - name: Load Dataset
        run: |
          jupyter nbconvert --to notebook --execute --FilesWriter.build_directory=. "${GITHUB_WORKSPACE}/Notebooks/1_load_data.ipynb"

      - name: Feature Engineering
        run: |
          jupyter nbconvert --to notebook --execute --FilesWriter.build_directory=. "${GITHUB_WORKSPACE}/Notebooks/feature_engineering.ipynb"
